resources:
- repo: self
queue:
  name: Series5-docker
  condition: succeeded()
steps:
- powershell: . build.ps1 CI 
  displayName: CI
  env:
    DockerUsername: $(DockerUsername)
    DockerPassword: $(DockerPassword)

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunner: NUnit
    testResultsFiles: '$(TestResultsFilePath)'
  condition: succeededOrFailed()

