resources:
  repositories:
    - repository: mysrc
      type: github
      endpoint: Github
      name: christianacca/docker-aspnet-sample
queue: Series5-docker
name: $(Date:yyyyMMdd).$(BuildID)

steps:
- powershell: .\build.ps1 CI
  displayName: CI
  name: CI
  env:
    DockerUsername: $(DockerUsername)
    DockerPassword: $(DockerPassword)

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunner: NUnit
    testResultsFiles: '**\Test*.xml'
    searchFolder: '$(CI.TestResultsSearchPath)'
    mergeTestResults: true
  condition: succeededOrFailed()