version: '3.4'

services:
  db:
    image: ${DB_IMAGE_TAG:-christianacca/mssql-server-windows-express}
    environment:
      - sa_password=This1sthesapassword1
      - ACCEPT_EULA=Y
    volumes:
      # - db-data:C:\sql\userdbs\data
      # - db-log:C:\sql\userdbs\log
      - db-backup:C:\sql\backup

  web-app:
    image: christianacca/aspnetapp-sample:${VERSION:-latest}
    environment:
      - sa_password=This1sthesapassword1
      - DB_SERVER=db
    depends_on:
      - db


volumes:
  # db-data:
  # db-log:
  db-backup: